# Initial migration for AutoStock
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Brand',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True))]),
        migrations.CreateModel(name='Category',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True))]),
        migrations.CreateModel(name='Supplier',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('cnpj',models.CharField(blank=True,max_length=18)),('phone',models.CharField(blank=True,max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('lead_time_days',models.PositiveIntegerField(default=7))]),
        migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('sku',models.CharField(max_length=60,unique=True)),('name',models.CharField(max_length=180)),('cost_price',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('sale_price',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('quantity',models.IntegerField(default=0)),('min_stock',models.PositiveIntegerField(default=0)),('location',models.CharField(blank=True,max_length=80)),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('brand',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='products',to='inventory.brand')),('category',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='products',to='inventory.category')),('supplier',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='products',to='inventory.supplier'))]),
        migrations.CreateModel(name='Sale',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('customer_name',models.CharField(blank=True,max_length=160)),('total',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='SaleItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.PositiveIntegerField()),('unit_price',models.DecimalField(decimal_places=2,max_digits=12)),('subtotal',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='inventory.product')),('sale',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='inventory.sale'))]),
        migrations.CreateModel(name='StockMovement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('movement_type',models.CharField(choices=[('IN','Entrada'),('OUT','Saída'),('ADJ','Ajuste')],max_length=3)),('quantity',models.PositiveIntegerField()),('unit_cost',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('note',models.CharField(blank=True,max_length=255)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='movements',to='inventory.product'))]),
    ]
